name: stream_video
description: Stream Video.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # C
  connectivity_plus: ^2.2.0

  # D
  dotted_decoration: ^2.0.0

  # F
  file_picker: ^4.3.3
  filesize: ^2.0.1
  fluttertoast: ^8.0.8
  flutter_spinkit: ^5.1.0

  # G
  get_it: ^7.2.0

  # L
  lottie: ^1.2.1

  # S
  socket_io_client: ^1.0.1

  # P
  provider: ^6.0.2
  path_provider: ^2.0.9

  # V
  video_compress: ^3.1.0
  video_player: ^2.2.18
  
  # W
  web_socket_channel: ^2.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/lotties/
