class AppConstants { 
  static const String firebaseKey = 'AAAALAULPvE:APA91bH3xGzHcM3tWs5CKOyzdcfmjt8_z_htqRTSqlE47Cx6BmY8oTTQJ5QJngIlYzz5w-sbSyB1iigaQIonS3yDZVSVlvwDzH7rk4tIegawxlwjlt3_9rOnolDlsGh_Dnk1THSRKmnq';
}